### ISSUE TITLE
When clicking links in the wiki the content gets clipped by the header

### ISSUE THREAD

**Issue by L1lith** [melonjs/melonjs.org#19]
This happens when using links containing `#` are clicked. The page scrolls to put it on the top of the page, but the header is on top so the content gets obscured.

**Comment by L1lith** [comment]
We might be able to work around it by making it so the header isn't sticky and instead stays still, and then instead of scrolling the whole body we could only scroll the page content instead

**Comment by obiot** [comment]
or make the navbar disappear when we access the wiki content ?

**Comment by L1lith** [comment]
I've resolved this by now by adding a scroll offset to the HTML element globally
