### ISSUE TITLE
Background game is not mobile-friendly

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonjs.org#5]
I tried showing off the website to a friend while out on coffee break. It would have been an awesome demo, except the background game **prevents scrolling** the page, and there's no way to play the game with touchscreen controls.

My proposal here is to create a new game that meets the following goals:

1. Fits into the website *seamlessly*
    * e.g. It looks like it belongs, not out-of-place or forced to fit.
    * Audio and music fit; fading with the DOM elements, etc.
2. Is controllable on Desktop and mobile platforms equally well (touch, keyboard/mouse, gamepad)
3. Uses auto renderer, to take advantage of WebGL when available.
    * This is necessary for smooth scrolling.
4. Does not link to cross-origin code.
    * Prevent all kinds of problems with repo organization (custom game is not necessary outside of the website repo)
    * Prevents cross-origin problems with SSL and WebGL.

**Comment by obiot** [comment]
This probably does not help as well :)
https://github.com/melonjs/melonjs.org/blob/gh-pages/index.html#L338

**Comment by parasyte** [comment]
Now this is a problem: https://github.com/melonjs/melonJS/blob/62df6deb2006d6399a5a3418fd15af25277c8b75/src/system/device.js#L30-L38

**Comment by obiot** [comment]
oh indeed, that other code should not even be there actually

**Comment by obiot** [comment]
would it be "clean" enough to add a `me.device.enableSwipeOnWebView()` function, that would basically remove the eventListener on touchmove ?

with that in place all we need then is to call the 3 following functions before [game.onload()](https://github.com/melonjs/melonjs.org/blob/gh-pages/index.html#L332) :
```javascript
// enable cross-origin image loading
me.loader.crossOrigin = "anonymous"
// configure the baseURL for the loader
me.loader.setBaseURL("*", "http://melonjs.github.io/melonJS/examples/platformer/");
// enable swipe on mobile device
me.device.enableSwipeOnWebView();
```
and we can run any games, from anywhere !

**Comment by parasyte** [comment]
Maybe it can be a part of the fullscreen API ... It seems elegant, at first glance. Maybe I'm missing something.

But yeah, we can include a separate method specially for disabling swipe, too. Just call it by default with fullscreen. :)

**Comment by obiot** [comment]
so I did that right now :
https://github.com/melonjs/melonJS/commit/ba4efc743754ad7ed748cd2a5025ee36c8c04d1c

and adding the following in the index.html, allows to enable swipe on webview :
````javascript
      // enable swipe on mobile device
      if (me.device.isMobile && !me.device.cocoon) {
          // Prevent the webview from moving on a swipe
          me.device.enableSwipe();
      }
````

not sure though about the fullscreen API, as on mobile it's not really supported, is it ?

**Comment by obiot** [comment]
4.1.0 is ready for a quick release, and fix the website now, including running the stock platformer from the example repo :) /meLikeIt :)

**Comment by obiot** [comment]
closing this issue following the latest website update. Background game has been remove, as the website has been modernised and simplified (demo game available through the "demo" button in the header)
